/**
 * OVF descriptor generation and rewriting.
 *
 * Proxmox imports an OVA by reading the OVF descriptor inside it. A zipped
 * VMware folder usually has no OVF at all — just a `.vmx` and some `.vmdk`s —
 * so we write one from what the VMX told us. That turns the most common upload
 * shape into something Proxmox can ingest natively, instead of a page of
 * commands for the admin to run over SSH.
 *
 * When the bundle *does* ship an OVF, we keep it and only rewrite the `href`
 * attributes, because repackaging flattens the directory tree.
 */
import path from "path";
import type { BundleFile, GuestSpec } from "./types";

/** DMTF's CIM OS identifiers. Proxmox only reads these as a hint. */
const CIM_OS_ID = (family: GuestSpec["family"]): number => {
  if (family === "windows") return 1; // "Other" — deliberately vague; ostype is set explicitly at create time
  if (family === "linux") return 36;
  return 0;
};

const escapeXml = (value: string): string =>
  value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

/**
 * Build an OVF envelope describing `spec`. `diskFiles` are the flat names the
 * disks will have inside the repackaged OVA, in attachment order.
 */
export function buildOvf(spec: GuestSpec, diskFiles: Array<{ flatName: string; size: number; capacityBytes: number | null }>): string {
  const references = diskFiles
    .map((d, i) => `    <File ovf:href="${escapeXml(d.flatName)}" ovf:id="file${i + 1}" ovf:size="${d.size}"/>`)
    .join("\n");

  const disks = diskFiles
    .map((d, i) => {
      // A capacity we couldn't read falls back to the on-disk size. It only has
      // to be >= the real size; qemu-img reads the true geometry anyway.
      const capacity = d.capacityBytes && d.capacityBytes > 0 ? d.capacityBytes : d.size;
      return (
        `    <Disk ovf:capacity="${capacity}" ovf:capacityAllocationUnits="byte" ` +
        `ovf:diskId="vmdisk${i + 1}" ovf:fileRef="file${i + 1}" ` +
        `ovf:format="http://www.vmware.com/interfaces/specifications/vmdk.html#streamOptimized"/>`
      );
    })
    .join("\n");

  const diskItems = diskFiles
    .map(
      (_, i) => `        <Item>
          <rasd:AddressOnParent>${i}</rasd:AddressOnParent>
          <rasd:ElementName>Hard Disk ${i + 1}</rasd:ElementName>
          <rasd:HostResource>ovf:/disk/vmdisk${i + 1}</rasd:HostResource>
          <rasd:InstanceID>${100 + i}</rasd:InstanceID>
          <rasd:Parent>3</rasd:Parent>
          <rasd:ResourceType>17</rasd:ResourceType>
        </Item>`
    )
    .join("\n");

  const name = escapeXml(spec.name);

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by WCTARange from a VMware bundle that shipped no OVF descriptor. -->
<Envelope xmlns="http://schemas.dmtf.org/ovf/envelope/1"
          xmlns:ovf="http://schemas.dmtf.org/ovf/envelope/1"
          xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData"
          xmlns:vssd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData"
          xmlns:vmw="http://www.vmware.com/schema/ovf"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <References>
${references}
  </References>
  <DiskSection>
    <Info>Virtual disk information</Info>
${disks}
  </DiskSection>
  <NetworkSection>
    <Info>The list of logical networks</Info>
    <Network ovf:name="bridged">
      <Description>The bridged network</Description>
    </Network>
  </NetworkSection>
  <VirtualSystem ovf:id="${name}">
    <Info>A virtual machine</Info>
    <Name>${name}</Name>
    <OperatingSystemSection ovf:id="${CIM_OS_ID(spec.family)}" vmw:osType="${escapeXml(spec.ostype)}">
      <Info>The kind of installed guest operating system</Info>
      <Description>${escapeXml(spec.osLabel)}</Description>
    </OperatingSystemSection>
    <VirtualHardwareSection>
      <Info>Virtual hardware requirements</Info>
      <System>
        <vssd:ElementName>Virtual Hardware Family</vssd:ElementName>
        <vssd:InstanceID>0</vssd:InstanceID>
        <vssd:VirtualSystemIdentifier>${name}</vssd:VirtualSystemIdentifier>
        <vssd:VirtualSystemType>vmx-14</vssd:VirtualSystemType>
      </System>
      <Item>
        <rasd:AllocationUnits>hertz * 10^6</rasd:AllocationUnits>
        <rasd:Description>Number of Virtual CPUs</rasd:Description>
        <rasd:ElementName>${spec.cores} virtual CPU(s)</rasd:ElementName>
        <rasd:InstanceID>1</rasd:InstanceID>
        <rasd:ResourceType>3</rasd:ResourceType>
        <rasd:VirtualQuantity>${spec.cores}</rasd:VirtualQuantity>
      </Item>
      <Item>
        <rasd:AllocationUnits>byte * 2^20</rasd:AllocationUnits>
        <rasd:Description>Memory Size</rasd:Description>
        <rasd:ElementName>${spec.memoryMb}MB of memory</rasd:ElementName>
        <rasd:InstanceID>2</rasd:InstanceID>
        <rasd:ResourceType>4</rasd:ResourceType>
        <rasd:VirtualQuantity>${spec.memoryMb}</rasd:VirtualQuantity>
      </Item>
      <Item>
        <rasd:Address>0</rasd:Address>
        <rasd:ElementName>SCSI Controller 0</rasd:ElementName>
        <rasd:InstanceID>3</rasd:InstanceID>
        <rasd:ResourceSubType>lsilogic</rasd:ResourceSubType>
        <rasd:ResourceType>6</rasd:ResourceType>
      </Item>
${diskItems}
      <Item>
        <rasd:AddressOnParent>0</rasd:AddressOnParent>
        <rasd:AutomaticAllocation>true</rasd:AutomaticAllocation>
        <rasd:Connection>bridged</rasd:Connection>
        <rasd:ElementName>Network adapter 1</rasd:ElementName>
        <rasd:InstanceID>200</rasd:InstanceID>
        <rasd:ResourceSubType>${escapeXml(spec.nicModel === "vmxnet3" ? "VmxNet3" : "E1000")}</rasd:ResourceSubType>
        <rasd:ResourceType>10</rasd:ResourceType>
      </Item>
      <vmw:Config ovf:required="false" vmw:key="firmware" vmw:value="${spec.firmware === "ovmf" ? "efi" : "bios"}"/>
    </VirtualHardwareSection>
  </VirtualSystem>
</Envelope>
`;
}

/**
 * Point an existing OVF's `ovf:href` values at the flat names the repackaged
 * OVA will use. Exporters happily write `disks/vm-disk1.vmdk`, and a tar entry
 * named `vm-disk1.vmdk` wouldn't match.
 */
export function rewriteOvfHrefs(ovfXml: string, files: BundleFile[]): { xml: string; rewritten: string[] } {
  const byBase = new Map<string, BundleFile>();
  for (const file of files) byBase.set(path.posix.basename(file.name).toLowerCase(), file);

  const rewritten: string[] = [];
  const xml = ovfXml.replace(/(ovf:href\s*=\s*)(["'])([^"']+)\2/gi, (whole, prefix: string, quote: string, href: string) => {
    const decoded = decodeURIComponent(href).replace(/\\/g, "/");
    const match = byBase.get(path.posix.basename(decoded).toLowerCase());
    if (!match || match.flatName === href) return whole;
    rewritten.push(`${href} → ${match.flatName}`);
    return `${prefix}${quote}${match.flatName}${quote}`;
  });

  return { xml, rewritten };
}
